# Drugi domaći zadatak iz PPGR

Student: Teodora Nićković, mi16057

Tema: Izračunavanje matrice projektivnog preslikavanja na osnovu zadatih tačaka

In [65]:
import numpy as np
from numpy import linalg as la
import math

## 1. Naivni algoritam

In [66]:
def naive_algorithm_canon(points):
    A = points[0]
    B = points[1]
    C = points[2]
    D = points[3]
    
    A0 = (1, 0, 0)
    B0 = (0, 1, 0)
    C0 = (0, 0, 1)
    D0 = (1, 1, 1)
    
    delta = [ [A[0], B[0], C[0]],
              [A[1], B[1], C[1]],
              [A[2], B[2], C[2]] ]
    
    delta1 = [ [D[0], B[0], C[0]],
               [D[1], B[1], C[1]],
               [D[2], B[2], C[2]] ]
    
    
    delta2 = [ [A[0], D[0], C[0]],
               [A[1], D[1], C[1]],
               [A[2], D[2], C[2]] ]
    
    delta3 = [ [A[0], B[0], D[0]],
               [A[1], B[1], D[1]],
               [A[2], B[2], D[2]] ]
    
    delta_det = la.det(delta)
    delta1_det = la.det(delta1)
    delta2_det = la.det(delta2)
    delta3_det = la.det(delta3)
    
    lambda1 = delta1_det/delta_det
    lambda2 = delta2_det/delta_det
    lambda3 = delta3_det/delta_det
    
    
    P = [[lambda1*x for x in A],
         [lambda2*x for x in B],
         [lambda3*x for x in C]]
    
    
    return np.transpose(P)

def naive_algorithm(points, points_proj):
    P1 = naive_algorithm_canon(points)
    P2 = naive_algorithm_canon(points_proj)

    P1_inv = la.inv(P1)
    P = np.matmul(P2, P1_inv)
    
    return P

### Testiranje naivnog algoritma na test primeru iz zadatka

In [67]:
n = 4
points = []
for i in range(n):
    print('Unesite koordinate originalne tacke', i+1, ':')
    a1 = int(input())
    a2 = int(input())
    a3 = int(input())
    A = [a1, a2, a3]
    points.append(A)
    
points_proj = []
for i in range(n):
    print('Unesite koordinate tacke slike', i+1)
    ap1 = int(input())
    ap2 = int(input())
    ap3 = int(input())
    Ap = [ap1, ap2, ap3]
    points_proj.append(Ap)

P = naive_algorithm(points, points_proj)

Unesite koordinate originalne tacke 1 :


 -3
 -1
 1


Unesite koordinate originalne tacke 2 :


 3
 -1
 1


Unesite koordinate originalne tacke 3 :


 1
 1
 1


Unesite koordinate originalne tacke 4 :


 -1
 1
 1


Unesite koordinate tacke slike 1


 -2
 -1
 1


Unesite koordinate tacke slike 2


 2
 -1
 1


Unesite koordinate tacke slike 3


 2
 1
 1


Unesite koordinate tacke slike 4


 -2
 1
 1


In [68]:
print("Matrica preslikavanja: ")
print(np.around(P, 5))

Matrica preslikavanja: 
[[ 2. -0.  0.]
 [-0.  2. -1.]
 [ 0. -1.  2.]]


## 2. DLT algoritam

In [33]:
def big_matrix(t1, t2):
    M = np.matrix(
        [ [0, 0, 0, -t2[2]*t1[0], -t2[2]*t1[1], -t2[2]*t1[2], t2[1]*t1[0], t2[1]*t1[1], t2[1]*t1[2]],
         [t2[2]*t1[0], t2[2]*t1[1], t2[2]*t1[2], 0, 0, 0, -t2[0]*t1[0], -t2[0]*t1[1], -t2[0]*t1[2]]
        ])
    return M

def dlt_algorithm(points, points_proj):
    A = []
    n = len(points)
    for i in range(n):
        a = big_matrix(points[i], points_proj[i])
        
        if(i > 0):
            A = np.concatenate((A, a), axis = 0)
        else:
            A = a
    
    U, D, Vt = la.svd(A, full_matrices=True)
    V = np.transpose(Vt)
    V = V[:, -1]
    P = V.reshape(3,3)
    
    return P

### Testiranje DLT algoritma na test primeru iz zadatka

In [37]:
n = int(input("Unesite broj originalnih tacaka: "))

points = []
for i in range(n):
    print('Unesite koordinate originalne tacke', i+1, ': ')
    a1 = int(input())
    a2 = int(input())
    a3 = int(input())
    A = [a1, a2, a3]
    points.append(A)
    
points_proj = []
for i in range(n):
    print('Unesite koordinate tacke slike', i+1, ': ')
    ap1 = int(input())
    ap2 = int(input())
    ap3 = int(input())
    Ap = [ap1, ap2, ap3]
    points_proj.append(Ap)

Pdlt = dlt_algorithm(points, points_proj)

Unesite broj originalnih tacaka:  6


Unesite koordinate originalne tacke 1 : 


 -3
 -1
 1


Unesite koordinate originalne tacke 2 : 


 3
 -1
 1


Unesite koordinate originalne tacke 3 : 


 1
 1
 1


Unesite koordinate originalne tacke 4 : 


 -1
 1
 1


Unesite koordinate originalne tacke 5 : 


 1
 2
 3


Unesite koordinate originalne tacke 6 : 


 -8
 -2
 1


Unesite koordinate tacke slike 1 : 


 -2
 -1
 1


Unesite koordinate tacke slike 2 : 


 2
 -1
 1


Unesite koordinate tacke slike 3 : 


 2
 1
 1


Unesite koordinate tacke slike 4 : 


 -2
 1
 1


Unesite koordinate tacke slike 5 : 


 2
 1
 4


Unesite koordinate tacke slike 6 : 


 -16
 -5
 4


In [38]:
print("Matrica preslikavanja: ")
print(np.around(Pdlt, 5))

Matrica preslikavanja: 
[[-0.53452  0.      -0.     ]
 [ 0.      -0.53452  0.26726]
 [-0.       0.26726 -0.53452]]


### Poređenje naivnog i DLT algoritma

(Sa vežbi):
Pošto smo slike poslednje 2 tačke pronašli množenjem sa matricom P, trebalo bi da se rezultati naivnog i DLT algoritma poklapaju, tj. da su matrice P i Pdlt proporcionalne (proporcionalne matrice zadaju isto projektivno preslikavanje).

Ovde ćemo odmah videti da su iste, ali u slučaju da se to ne vidi, matrice poredimo tako što podelimo Pdlt matricu sa Pdlt[1][1], a zatim pomnožimo sa P[1][1].

In [45]:
print('P: ')
print(P)

print('Pdlt: ')
print(Pdlt)

P: 
[[-5.34522484e-01  1.36070498e-15 -7.98395180e-16]
 [ 1.13931579e-16 -5.34522484e-01  2.67261242e-01]
 [-1.84633342e-16  2.67261242e-01 -5.34522484e-01]]
Pdlt: 
[[-5.34522484e-01  1.36070498e-15 -7.98395180e-16]
 [ 1.13931579e-16 -5.34522484e-01  2.67261242e-01]
 [-1.84633342e-16  2.67261242e-01 -5.34522484e-01]]


## DLT algoritam sa normalizacijom

In [56]:
def normalize(points):
    # CMS - center of mass (teziste)
    CMS = []
    affine_points = []
    n = len(points)
    for i in range(n):
        A = np.array(points[i])
        A = np.array([A[0]/A[2], A[1]/A[2]])
        affine_points.append(A)
        if(i > 0):
            CMS += A
        else:
            CMS = A
    CMS = CMS * np.array([1/n, 1/n])
    
    # Translacija
    T = np.matrix([ [1, 0, -CMS[0]],
                    [0, 1, -CMS[1]],
                    [0, 0, 1] ])
    
    # Homotetija
    lamb = 0
    for i in range(n):
        A = affine_points[i] 
        lamb += math.sqrt(A[0]*A[0] + A[1]*A[1])
    lamb = lamb / n
    
    h = math.sqrt(2) / lamb
    H = np.matrix([[h, 0, 0],
                   [0, h, 0],
                   [0, 0, 1]
                   ])
    
    # Matrica normalizacije
    N = np.matmul(H, T)
    return N

def dlt_normalize(points, points_proj):    
    T_matrix = normalize(points) 
    Tp_matrix = normalize(points_proj) 
    
    T_matrix = np.array(T_matrix).reshape((3,3))
    Tp_matrix = np.array(Tp_matrix).reshape((3,3))
  
    points = np.transpose(points)
    points_proj = np.transpose(points_proj)
    
    M_nadvuceno = T_matrix.dot(points) 
    Mp_nadvuceno = Tp_matrix.dot(points_proj) 
    
    M_nadvuceno = np.transpose(M_nadvuceno) 
    Mp_nadvuceno = np.transpose(Mp_nadvuceno) 
    dlt_matrix = dlt_algorithm(M_nadvuceno, Mp_nadvuceno) 
    
    dlt_matrix = np.array(dlt_matrix).reshape((3, 3))

    result = (np.linalg.inv(Tp_matrix)).dot(dlt_matrix).dot(T_matrix)
    return result

### Testiranje DLT algoritma sa normalizacijom

In [57]:
# Unos podataka
n = int(input("Unesite broj originalnih tacaka: "))
points = []
for i in range(n):
    print('Unesite koordinate originalne tacke', i+1, ': ')
    a1 = int(input())
    a2 = int(input())
    a3 = int(input())
    A = [a1, a2, a3]
    points.append(A)

points_proj = []
for i in range(n):
    print('Unesite koordinate tacke slike', i+1, ': ')
    ap1 = int(input())
    ap2 = int(input())
    ap3 = int(input())
    Ap = [ap1, ap2, ap3]
    points_proj.append(Ap)

Pndlt = dlt_normalize(points, points_proj)

Unesite broj originalnih tacaka:  6


Unesite koordinate originalne tacke 1 : 


 -3
 -1
 1


Unesite koordinate originalne tacke 2 : 


 3
 -1
 1


Unesite koordinate originalne tacke 3 : 


 1
 1
 1


Unesite koordinate originalne tacke 4 : 


 -1
 1
 1


Unesite koordinate originalne tacke 5 : 


 1
 2
 3


Unesite koordinate originalne tacke 6 : 


 -8
 -2
 1


Unesite koordinate tacke slike 1 : 


 -2
 -1
 1


Unesite koordinate tacke slike 2 : 


 2
 -1
 1


Unesite koordinate tacke slike 3 : 


 2
 1
 1


Unesite koordinate tacke slike 4 : 


 -2
 1
 1


Unesite koordinate tacke slike 5 : 


 2
 1
 4


Unesite koordinate tacke slike 6 : 


 -16
 -5
 4


In [59]:
print("Matrica preslikavanja: ")
print(np.around(Pndlt, 5))

Matrica preslikavanja: 
[[ 0.36209 -0.       0.     ]
 [-0.       0.36209 -0.18105]
 [ 0.      -0.18105  0.36209]]


## Celokupno testiranje sa tačkama iz fajla primer3.nb.pdf

In [62]:
a = [-3, 2, 1]
b = [-2, 5, 2]
c = [1, 0, 3]
d = [-7, 3, 1]
e = [2, 1, 2]
f = [-1, 2, 1]
g = [1, 1, 1]

ap = [11, -12, 7]
bp = [25, -8, 9]
cp = [15, 4, 17]
dp = [14, -28, 10]
ep = [13, 8, 9]
fp = [11, -4, 5]
gp = [8.02, 4, 4]

In [82]:
# Testiranje naivnog algoritma
P1 = naive_algorithm([a,b,c,d], [ap, bp, cp, dp])
print('Matrica proj preslikavanja za naivni alg. za [a,b,c,d]: ')
print(np.around(P1, 3))

P2 = naive_algorithm([a,b,e,d], [ap, bp, ep, dp])
print('Matrica proj preslikavanja za naivni alg. za [a,b,e,d]: ')
print(np.around(P2, 3))

Matrica proj preslikavanja za naivni alg. za [a,b,c,d]: 
[[ 0.  3.  5.]
 [ 4. -0.  0.]
 [-1. -1.  6.]]
Matrica proj preslikavanja za naivni alg. za [a,b,e,d]: 
[[ 0.  3.  5.]
 [ 4. -0.  0.]
 [-1. -1.  6.]]


In [129]:
# Testiranje DLT algoritma
Pdlt_test = dlt_algorithm([a,b,c,d,e,f,g], [ap,bp,cp,dp,ep,fp,gp])
print('Matrica proj preslikavanja za DLT alg: ')
print(np.around(Pdlt_test, 3))

print()
m = Pdlt_test * 3 / Pdlt_test[0,1]
print(m)

Matrica proj preslikavanja za DLT alg: 
[[ 0.     0.32   0.533]
 [ 0.426 -0.    -0.   ]
 [-0.107 -0.107  0.64 ]]

[[ 4.97352886e-04  3.00000000e+00  4.99603472e+00]
 [ 3.99778538e+00 -1.89543630e-04 -2.76689017e-04]
 [-9.99295809e-01 -9.98580867e-01  5.99549835e+00]]


In [86]:
# Testiranje modifikovanog DLT algoritma
Pndlt_test = dlt_normalize([a,b,c,d,e,f,g], [ap,bp,cp,dp,ep,fp,gp])
print('Matrica proj preslikavanja za modifikovani DLT alg: ')
print(np.around(Pdlt_test, 3))

Matrica proj preslikavanja za modifikovani DLT alg: 
[[ 0.     0.32   0.533]
 [ 0.426 -0.    -0.   ]
 [-0.107 -0.107  0.64 ]]


In [114]:
# Testiranje invarijantnosti DLT u odnosu na promenu coord
cc = [[0,1,2], [-1, 0, 3], [0,0,1]]
points = [a,b,c,d,e,f,g]
points_proj = [ap,bp,cp,dp,ep,fp,gp]
n = len(points)

norig = [list(np.matmul(cc,v)) for v in points]
nslike = [list(np.matmul(cc,v)) for v in points_proj]

In [115]:
print(norig)
print(nslike)

[[4, 6, 1], [9, 8, 2], [6, 8, 3], [5, 10, 1], [5, 4, 2], [4, 4, 1], [3, 2, 1]]
[[2, 10, 7], [10, 2, 9], [38, 36, 17], [-8, 16, 10], [26, 14, 9], [6, 4, 5], [12.0, 3.9800000000000004, 4.0]]


In [132]:
# Prvo odredimo matricu preslikavanja u novom koo sistemu
m1 = dlt_algorithm(norig, nslike)
# Vratimo u stari koo sistem, i dobijamo matricu preslikavanja u starom
# koo sistemu
m1s = np.matmul(la.inv(cc), np.matmul(m1, cc))
nm1 = m1s * 3 / m1s[0,1]

print('Matrica preslikavanja za izmenjene koo: ')
print(nm1)

print('Originalna matrica preslikavanja: ')
print(m)

Matrica preslikavanja za izmenjene koo: 
[[ 4.96620099e-04  3.00000000e+00  4.99604404e+00]
 [ 3.99779004e+00 -1.89349457e-04 -2.75649443e-04]
 [-9.99297373e-01 -9.98584504e-01  5.99550913e+00]]
Originalna matrica preslikavanja: 
[[ 4.97352886e-04  3.00000000e+00  4.99603472e+00]
 [ 3.99778538e+00 -1.89543630e-04 -2.76689017e-04]
 [-9.99295809e-01 -9.98580867e-01  5.99549835e+00]]


Vidimo da se matrica razlikuje malo od pocetne, pa zato DLT nije invarijantan u odnosu na promenu koo.

In [133]:
# Testiranje invarijantnosti normalizovanog DLT u odnosu na promenu coord
cc = [[0,1,2], [-1, 0, 3], [0,0,1]]
points = [a,b,c,d,e,f,g]
points_proj = [ap,bp,cp,dp,ep,fp,gp]
n = len(points)

norig = [list(np.matmul(cc,v)) for v in points]
nslike = [list(np.matmul(cc,v)) for v in points_proj]

# Prvo odredimo matricu preslikavanja u novom koo sistemu
m2 = dlt_normalize(norig, nslike)
# Vratimo u stari koo sistem, i dobijamo matricu preslikavanja u starom
# koo sistemu
m2s = np.matmul(la.inv(cc), np.matmul(m2, cc))
nm2 = m2s * 3 / m2s[0,1]

print('Matrica preslikavanja za izmenjene koo: ')
print(nm2)

print('Originalna matrica preslikavanja: ')
print(m)

Matrica preslikavanja za izmenjene koo: 
[[ 4.96727994e-04  3.00000000e+00  4.99603778e+00]
 [ 3.99778791e+00 -1.89007930e-04 -2.76811706e-04]
 [-9.99296756e-01 -9.98582323e-01  5.99550206e+00]]
Originalna matrica preslikavanja: 
[[ 4.97352886e-04  3.00000000e+00  4.99603472e+00]
 [ 3.99778538e+00 -1.89543630e-04 -2.76689017e-04]
 [-9.99295809e-01 -9.98580867e-01  5.99549835e+00]]


(Nisu potpuno iste, ali moguce da se ovo izgubilo u zaokruzivanju posto su razlike na visokim decimalama). Iz ovoga mozemo zakljuciti da je normalizovani DLT invarijantan na promenu koo.